### PR TITLE
Change deprecated componentWillMount method to componentDidMount.

### PR DESCRIPTION
**Pull request by sheparddw**
As noted in issue https://github.com/livechat/react-livechat/issues/42

### CODE REVIEW

**Comment by jamesmosier** [comment]
Anything I can do to help land this @venits / @quarties? 😄 

Even if it is just renaming the lifecycle to `UNSAFE_componentWillMount` which will at least suppress the React dev warnings and reduce any chance of regressions.

**Comment by diegoleft** [comment]
Can anybody accept this, please?

**Comment by vzaidman** [comment]
hey!
the library spams out console. please fix it!

**Comment by walaszczykm** [comment]
Hello everyone 👋 

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters) 🙂 

From now on it will be the official, actively maintained repository for each framework-specific package that allows easy integration of LiveChat Chat Widget. **The Hooks API is one part of the new React package:** [@livechat/widget-react](http://npm.im/@livechat/widget-react).

In new implementation the class components and React lifecycle methods are no longer used instead we use function components and Hooks which will resolve all deprecation warnings related to them 😉

**Pull request closed without merging**
