### PR TITLE
LiveChat using hooks - redesigned

### PR DESCRIPTION
**Pull request by turkus**

### CODE REVIEW

**Comment by turkus** [comment]
Hi @venits,
 I have Christmas gift for you :) Could you take a look?

**Comment by iamchrismiller** [comment]
Any chance in this getting merged any time soon?

**Comment by diego-hourly** [comment]
is this getting merge any time soon?

**Comment by walaszczykm** [comment]
Hello everyone 👋 

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters) 🙂 

From now on it will be the official, actively maintained repository for each framework-specific package that allows easy integration of LiveChat Chat Widget. The Hooks API is one part of the new React package: [@livechat/widget-react](http://npm.im/@livechat/widget-react)

We have prepared not only the main function component (to not enforce transpilation of classes) `LiveChatWidget` which offers similar possibilities as the one from this package but additionally, we export dedicated set of Rect Hooks which allows consuming reactive data from Chat Widget from any place in the application.

**Pull request closed without merging**
